Repository KNU-CSE-APP/Server, pull requests merged in 2021-08, with the labels that each got.

#53 FEAT: 프로필 이미지 등록/변경 기능 구현
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/dto/MemberDto.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/member/service/MemberService.java
Labels: enhancement

#57 FIX: 테스트코드 주석처리
  src/main/java/com/knu/cse/classroom/dto/DeleteRoomDTO.java
  src/test/java/com/knu/cse/classroom/service/ClassRoomServiceTest.java
  src/test/java/com/knu/cse/reservation/service/ReservationServiceTest.java
Labels: Test, bug

#56 FEAT: Commnet Service 추가(댓글작성,삭제,수정,답글작성,삭제,수정)
  src/main/java/com/knu/cse/comment/controller/CommentController.java
  src/main/java/com/knu/cse/comment/domain/Comment.java
  src/main/java/com/knu/cse/comment/domain/CommentDTO.java
  src/main/java/com/knu/cse/comment/dto/CommentDto.java
  src/main/java/com/knu/cse/comment/dto/CommentForm.java
  src/main/java/com/knu/cse/comment/dto/ReplyForm.java
  src/main/java/com/knu/cse/comment/repository/CommentRepository.java
  src/main/java/com/knu/cse/comment/service/CommentService.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/reply/domain/Reply.java
  src/test/java/com/knu/cse/comment/service/CommentServiceTest.java
Labels: enhancement

#58 FEAT: 내가 작성한 게시물 조회 기능 구현 및 리팩토링
  src/main/java/com/knu/cse/board/controller/BoardController.java
  src/main/java/com/knu/cse/board/domain/Board.java
  src/main/java/com/knu/cse/board/repository/BoardRepository.java
  src/main/java/com/knu/cse/board/service/BoardService.java
Labels: Refactor, enhancement

#64 Feat: 비밀번호 변경 기능 추가
  src/main/java/com/knu/cse/email/service/AuthService.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/dto/ChangePasswordForm.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/member/service/MemberService.java
Labels: enhancement

#61 FEAT: 게시물 수정, 삭제 기능 추가
  src/main/java/com/knu/cse/board/controller/BoardController.java
  src/main/java/com/knu/cse/board/domain/Board.java
  src/main/java/com/knu/cse/board/service/BoardService.java
  src/main/java/com/knu/cse/comment/controller/CommentController.java
Labels: enhancement

#65 FIX: @Valid 검사 예외처리 수정
  src/main/java/com/knu/cse/errors/GeneralExceptionHandler.java
  src/main/java/com/knu/cse/member/dto/SignUpForm.java
Labels: bug

#62 REFACTOR : 불필요한 Lombok 어노테이션 제거 및 리팩토링
  src/main/java/com/knu/cse/board/domain/Board.java
  src/main/java/com/knu/cse/classroom/domain/ClassRoom.java
  src/main/java/com/knu/cse/classroom/service/ClassRoomService.java
  src/main/java/com/knu/cse/classseat/domain/ClassSeat.java
  src/main/java/com/knu/cse/comment/domain/Comment.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/model/Member.java
Labels: Refactor

#66 FIX: SecurityContextHolder를 사용해 JWT 인증
  src/main/java/com/knu/cse/board/controller/BoardController.java
  src/main/java/com/knu/cse/comment/controller/CommentController.java
  src/main/java/com/knu/cse/email/service/AuthService.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/security/SecurityMember.java
  src/main/java/com/knu/cse/reservation/controller/ReservationController.java
Labels: Refactor

#67 FIX : 비밀번호 변경 로직을 Controller에서 Service로 변경
  src/main/java/com/knu/cse/email/service/AuthService.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/service/MemberService.java
Labels: Refactor

#69 FEAT: Board List를 Page 처리하여 반환
  src/main/java/com/knu/cse/board/controller/BoardController.java
  src/main/java/com/knu/cse/board/repository/BoardRepository.java
  src/main/java/com/knu/cse/board/service/BoardService.java
Labels: enhancement

#68 FIX : ClassSeat Entity를 Builder 패턴 변경하면서 생긴 ClassRoom 연관관계 오류 해결
  src/main/java/com/knu/cse/classroom/service/ClassRoomService.java
Labels: bug

#71 FEAT: BoardDTO,CommentDTO에 날짜형식 변경 및 댓글갯수 변수 추가
  src/main/java/com/knu/cse/board/dto/BoardDto.java
  src/main/java/com/knu/cse/comment/dto/CommentDto.java
Labels: enhancement

#73 FIX : MeberDTO에 username, studentId 추가
  src/main/java/com/knu/cse/member/dto/MemberDto.java
Labels: enhancement

#74 FIX: 이미지 dir 생성
  src/main/java/com/knu/cse/image/S3UploadService.java
Labels: bug

#75 [#54] FEAT: 게시물에 해당하는 댓글을 조회할때, 답글은 댓글 객체에 포함되어 전달하도록 수정
  src/main/java/com/knu/cse/comment/controller/CommentController.java
  src/main/java/com/knu/cse/comment/dto/CommentDto.java
  src/main/java/com/knu/cse/comment/service/CommentService.java
Labels: enhancement

#72 FEAT: 회원탈퇴 기능 추가
  src/main/java/com/knu/cse/board/domain/Board.java
  src/main/java/com/knu/cse/comment/domain/Comment.java
  src/main/java/com/knu/cse/deletemember/domain/DeleteMember.java
  src/main/java/com/knu/cse/deletemember/repository/DeleteMemberRepository.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/dto/DeleteForm.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/member/service/MemberService.java
Labels: enhancement

#78 FEAT: 닉네임 수정시 댓글 및 게시물 저자 변경 / 프로필 이미지 초기화
  src/main/java/com/knu/cse/board/domain/Board.java
  src/main/java/com/knu/cse/board/service/BoardService.java
  src/main/java/com/knu/cse/comment/domain/Comment.java
  src/main/java/com/knu/cse/comment/service/CommentService.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/dto/UpdateNickNameAndImageDto.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/member/service/MemberService.java
Labels: enhancement

#77 FEAT: commetID로 댓글정보 확인
  src/main/java/com/knu/cse/comment/controller/CommentController.java
  src/main/java/com/knu/cse/comment/service/CommentService.java
Labels: enhancement

#79 FEAT: 비밀번호 찾기 기능 구현
  src/main/java/com/knu/cse/email/service/AuthService.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/dto/ChangePasswordForm.java
  src/main/java/com/knu/cse/member/dto/ValidatedPassowrdForm.java
  src/main/java/com/knu/cse/member/service/MemberService.java
Labels: enhancement

#80 FEAT: 내가 쓴 댓글/답글 각각 조회하는 기능 구현
  src/main/java/com/knu/cse/comment/controller/CommentController.java
  src/main/java/com/knu/cse/comment/dto/CommentDto.java
  src/main/java/com/knu/cse/comment/repository/CommentRepository.java
  src/main/java/com/knu/cse/comment/service/CommentService.java
Labels: enhancement

#81 FEAT: 회원 탈퇴와 로그아웃 기능 구현
  src/main/java/com/knu/cse/comment/controller/CommentController.java
  src/main/java/com/knu/cse/email/service/AuthService.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/service/MemberService.java
Labels: enhancement

#83 FEAT: 작성한 사람, 수정한 사람 Auditing 추가
  src/main/java/com/knu/cse/config/AppConfig.java
  src/main/java/com/knu/cse/config/Auditor.java
  src/main/java/com/knu/cse/member/dto/ValidatedPasswordForm.java
Labels: bug, enhancement

#84 FEAT: BoardDto에 멤버의 프로필이미지 추가
  src/main/java/com/knu/cse/board/domain/Board.java
  src/main/java/com/knu/cse/board/dto/BoardDto.java
Labels: enhancement

#85 FEAT: CommentDto에 멤버 프로필이미지 추가
  src/main/java/com/knu/cse/comment/domain/Comment.java
  src/main/java/com/knu/cse/comment/dto/CommentDto.java
Labels: enhancement

#88 FEAT : 강의실 전체 목록 반환 기능 구현
  src/main/java/com/knu/cse/classroom/controller/ClassRoomController.java
  src/main/java/com/knu/cse/classroom/dto/FindClassRoomDTO.java
  src/main/java/com/knu/cse/classroom/service/ClassRoomService.java
  src/main/java/com/knu/cse/reservation/service/ReservationService.java
  src/test/java/com/knu/cse/classroom/service/ClassRoomServiceTest.java
  src/test/java/com/knu/cse/reservation/service/ReservationServiceTest.java
Labels: enhancement, Test

#90 FEAT: board에 게시물 사진 등록 가능
  src/main/java/com/knu/cse/board/controller/BoardController.java
  src/main/java/com/knu/cse/board/domain/Board.java
  src/main/java/com/knu/cse/board/dto/BoardDto.java
  src/main/java/com/knu/cse/board/dto/BoardForm.java
  src/main/java/com/knu/cse/board/service/BoardService.java
  src/main/java/com/knu/cse/image/domain/Image.java
  src/main/java/com/knu/cse/image/repository/ImageRepository.java
  src/main/java/com/knu/cse/image/service/ImageService.java
Labels: enhancement

#86 REFACTOR: Member,ClassSeat,Reservation 지연로딩 적용
  src/main/java/com/knu/cse/classseat/domain/ClassSeat.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/reservation/domain/Reservation.java
Labels: Refactor

#91 FEAT: 이미지 유니크 파일네임 생성 및 이미지 삭제 기능 추가
  src/main/java/com/knu/cse/board/dto/BoardForm.java
  src/main/java/com/knu/cse/board/service/BoardService.java
  src/main/java/com/knu/cse/comment/dto/CommentForm.java
  src/main/java/com/knu/cse/comment/dto/ReplyForm.java
  src/main/java/com/knu/cse/image/S3UploadController.java
  src/main/java/com/knu/cse/image/S3UploadService.java
  src/main/java/com/knu/cse/image/service/FileUploadService.java
  src/main/java/com/knu/cse/image/service/ImageService.java
  src/main/java/com/knu/cse/image/service/S3Service.java
  src/main/java/com/knu/cse/member/service/MemberService.java
Labels: enhancement
