Repository KNU-CSE-APP/Server, pull requests merged in 2021-09, with the labels that each got.

#98 FIX: 게시물 파일첨부없이 작성하도록 수정 및 게시물 삭제 권한 관련 에러 해결
  src/main/java/com/knu/cse/board/service/BoardService.java
  src/main/java/com/knu/cse/config/AppConfig.java
  src/main/java/com/knu/cse/web/controller/WebBoardController.java
  src/main/resources/static/css/style.css
  src/main/resources/static/fonts/.DS_Store
  src/main/resources/static/fonts/font-awesome/css/font-awesome.css
  src/main/resources/static/fonts/font-awesome/css/font-awesome.min.css
  src/main/resources/static/fonts/font-awesome/fonts/FontAwesome.otf
  src/main/resources/static/fonts/font-awesome/fonts/fontawesome-webfont.eot
  src/main/resources/static/fonts/font-awesome/fonts/fontawesome-webfont.svg
  src/main/resources/static/fonts/font-awesome/fonts/fontawesome-webfont.ttf
  src/main/resources/static/fonts/font-awesome/fonts/fontawesome-webfont.woff
  src/main/resources/static/fonts/font-awesome/fonts/fontawesome-webfont.woff2
  src/main/resources/static/fonts/font-awesome/less/animated.less
  src/main/resources/static/fonts/font-awesome/less/bordered-pulled.less
  src/main/resources/static/fonts/font-awesome/less/core.less
  src/main/resources/static/fonts/font-awesome/less/fixed-width.less
  src/main/resources/static/fonts/font-awesome/less/font-awesome.less
  src/main/resources/static/fonts/font-awesome/less/icons.less
  src/main/resources/static/fonts/font-awesome/less/larger.less
  src/main/resources/static/fonts/font-awesome/less/list.less
  src/main/resources/static/fonts/font-awesome/less/mixins.less
  src/main/resources/static/fonts/font-awesome/less/path.less
  src/main/resources/static/fonts/font-awesome/less/rotated-flipped.less
  src/main/resources/static/fonts/font-awesome/less/screen-reader.less
  src/main/resources/static/fonts/font-awesome/less/stacked.less
  src/main/resources/static/fonts/font-awesome/less/variables.less
  src/main/resources/static/fonts/font-awesome/scss/_animated.scss
  src/main/resources/static/fonts/font-awesome/scss/_bordered-pulled.scss
  src/main/resources/static/fonts/font-awesome/scss/_core.scss
  src/main/resources/static/fonts/font-awesome/scss/_fixed-width.scss
  src/main/resources/static/fonts/font-awesome/scss/_icons.scss
  src/main/resources/static/fonts/font-awesome/scss/_larger.scss
  src/main/resources/static/fonts/font-awesome/scss/_list.scss
  src/main/resources/static/fonts/font-awesome/scss/_mixins.scss
  src/main/resources/static/fonts/font-awesome/scss/_path.scss
  src/main/resources/static/fonts/font-awesome/scss/_rotated-flipped.scss
  src/main/resources/static/fonts/font-awesome/scss/_screen-reader.scss
  src/main/resources/static/fonts/font-awesome/scss/_stacked.scss
  src/main/resources/static/fonts/font-awesome/scss/_variables.scss
  src/main/resources/static/fonts/font-awesome/scss/font-awesome.scss
  src/main/resources/static/plugin/bootstrap/css/bootstrap-theme.css
  src/main/resources/static/plugin/bootstrap/css/bootstrap-theme.css.map
  src/main/resources/static/plugin/bootstrap/css/bootstrap-theme.min.css
  src/main/resources/static/plugin/bootstrap/css/bootstrap-theme.min.css.map
  src/main/resources/static/plugin/bootstrap/css/bootstrap.css
  src/main/resources/static/plugin/bootstrap/css/bootstrap.css.map
  src/main/resources/static/plugin/bootstrap/css/bootstrap.min.css
  src/main/resources/static/plugin/bootstrap/css/bootstrap.min.css.map
  src/main/resources/static/plugin/bootstrap/fonts/glyphicons-halflings-regular.eot
  src/main/resources/static/plugin/bootstrap/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/plugin/bootstrap/fonts/glyphicons-halflings-regular.ttf
  src/main/resources/static/plugin/bootstrap/fonts/glyphicons-halflings-regular.woff
  src/main/resources/static/plugin/bootstrap/fonts/glyphicons-halflings-regular.woff2
  src/main/resources/static/plugin/bootstrap/js/bootstrap.js
  src/main/resources/static/plugin/bootstrap/js/bootstrap.min.js
  src/main/resources/static/plugin/bootstrap/js/npm.js
  src/main/resources/templates/board.html
  src/main/resources/templates/write.html
Labels: bug

#99 FEAT : boardlist, write css 적용
  src/main/resources/templates/boardList.html
  src/main/resources/templates/write.html
Labels: enhancement

#100 FEAT: Admin board 관련 컨트롤러에 관리자권한 확인하는 인터셉터 추가
  src/main/java/com/knu/cse/config/InterceptorConfig.java
  src/main/java/com/knu/cse/member/security/Auth.java
  src/main/java/com/knu/cse/member/security/AuthInterceptor.java
  src/main/java/com/knu/cse/web/controller/HomeController.java
  src/main/java/com/knu/cse/web/controller/WebBoardController.java
  src/main/resources/templates/unauthorized.html
Labels: enhancement

#101 FIX: 관리자 계정이 아니면 unauthorized로 redirect
  src/main/java/com/knu/cse/web/controller/HomeController.java
  src/main/java/com/knu/cse/web/controller/WebBoardController.java
  src/main/resources/templates/home.html
Labels: bug

#103 FIX : admin reservations 예약 기록 시간순 나열
  src/main/java/com/knu/cse/reservationsave/service/ReservationSaveService.java
  src/main/java/com/knu/cse/web/controller/WebReservationController.java
Labels: Refactor
