Repository KNU-CSE-APP/Server, pull requests merged in 2021-07, with the labels that each got.

#6 test for Jenkins CI/CD
  src/main/java/com/knu/cse/WebRestController.java
Labels: Establish

#8 ESTABLISH: test for Continuos Deploy
  src/main/java/com/knu/cse/WebRestController.java
Labels: Establish

#9 CHORE: remove empty test method
  src/test/java/com/knu/cse/MobileAppApplicationTests.java
Labels: Establish, bug

#14 FEAT: add User domain and Enum types
  src/main/java/com/knu/cse/MobileAppApplication.java
  src/main/java/com/knu/cse/base/BaseEntity.java
  src/main/java/com/knu/cse/base/BaseTimeEntity.java
  src/main/java/com/knu/cse/member/model/Gender.java
  src/main/java/com/knu/cse/member/model/Major.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/member/model/MemberRole.java
Labels: enhancement

#16 FEAT: 로그인 및 회원가입 기능 구현
  .gitignore
  build.gradle
  logs/local/app_server.log
  src/main/java/com/knu/cse/ApiResult/Response.java
  src/main/java/com/knu/cse/HealthCheckController.java
  src/main/java/com/knu/cse/MobileAppApplication.java
  src/main/java/com/knu/cse/config/AppConfig.java
  src/main/java/com/knu/cse/config/SecurityConfig.java
  src/main/java/com/knu/cse/email/service/AuthService.java
  src/main/java/com/knu/cse/email/service/EmailService.java
  src/main/java/com/knu/cse/email/service/MemberDetailsService.java
  src/main/java/com/knu/cse/email/util/CookieUtil.java
  src/main/java/com/knu/cse/email/util/JwtRequestFilter.java
  src/main/java/com/knu/cse/email/util/JwtUtil.java
  src/main/java/com/knu/cse/email/util/RedisUtil.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/dto/RequestVerifyEmail.java
  src/main/java/com/knu/cse/member/dto/SignInForm.java
  src/main/java/com/knu/cse/member/dto/SignUpForm.java
  src/main/java/com/knu/cse/member/dto/SignUpFormValidator.java
  src/main/java/com/knu/cse/member/model/Gender.java
  src/main/java/com/knu/cse/member/model/Major.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/member/model/MemberRole.java
  src/main/java/com/knu/cse/member/repository/MemberRepository.java
  src/main/java/com/knu/cse/member/security/SecurityMember.java
  src/main/resources/application.yml
  src/test/java/com/knu/cse/AuthServiceTest.java
Labels: enhancement

#18 FEAT: ClassSeat 도메인 추가
  src/main/java/com/knu/cse/classseat/domain/ClassSeat.java
  src/main/java/com/knu/cse/classseat/domain/Status.java
  src/main/java/com/knu/cse/classseat/repository/ClassSeatRepository.java
Labels: enhancement

#19 FEAT: ClassRoom 도메인 추가
  src/main/java/com/knu/cse/classroom/domain/Building.java
  src/main/java/com/knu/cse/classroom/domain/ClassRoom.java
  src/main/java/com/knu/cse/classroom/repository/ClassRoomRepository.java
  src/main/java/com/knu/cse/classseat/domain/ClassSeat.java
  src/main/java/com/knu/cse/classseat/domain/Status.java
  src/main/java/com/knu/cse/classseat/repository/ClassSeatRepository.java
Labels: enhancement

#20 FEAT: Reply 도메인 추가 및 충돌해결
  src/main/java/com/knu/cse/comment/domain/Comment.java
  src/main/java/com/knu/cse/reply/domain/Reply.java
Labels: enhancement

#21 FEAT: Reservation 도메인 추가
  src/main/java/com/knu/cse/classroom/domain/Building.java
  src/main/java/com/knu/cse/classroom/domain/ClassRoom.java
  src/main/java/com/knu/cse/classroom/repository/ClassRoomRepository.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/member/repository/MemberRepository.java
  src/main/java/com/knu/cse/reservation/domain/Reservation.java
  src/main/java/com/knu/cse/reservation/repository/ReservationRepository.java
  src/test/java/com/knu/cse/reservation/domain/ReservationTest.java
Labels: enhancement

#25 FIX: writeBoard,wirteComment,Comment 연관관계정의 메소드 수정
  src/main/java/com/knu/cse/board/domain/WriteBoard.java
  src/main/java/com/knu/cse/comment/domain/Comment.java
  src/main/java/com/knu/cse/comment/domain/WriteComment.java
Labels: bug

#27 FEAT: 로그인/회원가입/이메일 전송 기능
  .gitignore
  build.gradle
  logs/local/app_server.log
  src/main/java/com/knu/cse/ApiResult/Response.java
  src/main/java/com/knu/cse/HealthCheckController.java
  src/main/java/com/knu/cse/config/AppConfig.java
  src/main/java/com/knu/cse/config/SecurityConfig.java
  src/main/java/com/knu/cse/domain/Member.java
  src/main/java/com/knu/cse/domain/userConfig/Gender.java
  src/main/java/com/knu/cse/domain/userConfig/Major.java
  src/main/java/com/knu/cse/domain/userConfig/MemberRole.java
  src/main/java/com/knu/cse/email/service/AuthService.java
  src/main/java/com/knu/cse/email/service/EmailService.java
  src/main/java/com/knu/cse/email/service/MemberDetailsService.java
  src/main/java/com/knu/cse/email/util/CookieUtil.java
  src/main/java/com/knu/cse/email/util/JwtRequestFilter.java
  src/main/java/com/knu/cse/email/util/JwtUtil.java
  src/main/java/com/knu/cse/email/util/RedisUtil.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/dto/RequestVerifyEmail.java
  src/main/java/com/knu/cse/member/dto/SignInForm.java
  src/main/java/com/knu/cse/member/dto/SignUpForm.java
  src/main/java/com/knu/cse/member/dto/SignUpFormValidator.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/member/repository/MemberRepository.java
  src/main/java/com/knu/cse/member/security/SecurityMember.java
  src/main/resources/application.yml
  src/test/java/com/knu/cse/AuthServiceTest.java
Labels: enhancement

#30 FIX: 빌드 에러 원인 제거
  .gitignore
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/resources/application.yml
  src/test/java/com/knu/cse/AuthServiceTest.java
Labels: bug

#37 FIX: SingUpFrom, SignInForm 생성자 추가
  src/main/java/com/knu/cse/config/SecurityConfig.java
  src/main/java/com/knu/cse/member/dto/SignInForm.java
  src/main/java/com/knu/cse/member/dto/SignUpForm.java
Labels: bug

#38 FEAT: 강의실 예약 및 Test
  src/main/java/com/knu/cse/classroom/controller/ClassRoomController.java
  src/main/java/com/knu/cse/classroom/domain/ClassRoom.java
  src/main/java/com/knu/cse/classroom/dto/ClassRoomDTO.java
  src/main/java/com/knu/cse/classroom/repository/ClassRoomRepository.java
  src/main/java/com/knu/cse/classroom/service/ClassRoomService.java
  src/main/java/com/knu/cse/classseat/domain/ClassSeat.java
  src/main/java/com/knu/cse/classseat/repository/ClassSeatRepository.java
  src/main/java/com/knu/cse/classseat/service/ClassSeatService.java
  src/main/java/com/knu/cse/email/service/AuthService.java
  src/main/java/com/knu/cse/reservation/controller/ReservationController.java
  src/main/java/com/knu/cse/reservation/domain/FindReservationDTO.java
  src/main/java/com/knu/cse/reservation/domain/Reservation.java
  src/main/java/com/knu/cse/reservation/domain/ReservationDTO.java
  src/main/java/com/knu/cse/reservation/repository/ReservationRepository.java
  src/main/java/com/knu/cse/reservation/service/ReservationService.java
Labels: Test, enhancement

#33 FEAT: ApiFormat 및 GlobalException 추가
  build.gradle
  src/main/java/com/knu/cse/ApiResult/Response.java
  src/main/java/com/knu/cse/errors/GeneralExceptionHandler.java
  src/main/java/com/knu/cse/errors/NotFoundException.java
  src/main/java/com/knu/cse/errors/UnauthorizedException.java
  src/main/java/com/knu/cse/utils/ApiUtils.java
Labels: Establish, enhancement

#40 FEAT: writeComment,writeBoard 제거
  src/main/java/com/knu/cse/board/domain/Board.java
  src/main/java/com/knu/cse/board/domain/WriteBoard.java
  src/main/java/com/knu/cse/comment/domain/Comment.java
  src/main/java/com/knu/cse/comment/domain/WriteComment.java
  src/main/java/com/knu/cse/member/model/Member.java
Labels: Refactor

#36 FEAT: JWT 에서 claim 부분 복호화 기능 추가
  src/main/java/com/knu/cse/config/SecurityConfig.java
  src/main/java/com/knu/cse/email/service/AuthService.java
  src/main/java/com/knu/cse/email/service/MemberDetailsService.java
  src/main/java/com/knu/cse/email/util/JwtRequestFilter.java
  src/main/java/com/knu/cse/email/util/JwtUtil.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/dto/LoginSuccessDto.java
  src/main/java/com/knu/cse/member/dto/MemberDto.java
  src/main/java/com/knu/cse/member/dto/SignUpForm.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/member/repository/MemberRepository.java
  src/main/resources/application.yml
  src/test/java/com/knu/cse/AuthServiceTest.java
Labels: bug, enhancement

#42 FIX: SignUpForm add constructor
  src/main/java/com/knu/cse/member/dto/SignUpForm.java
Labels: bug

#43 FIX: ApiResult 포맷 통일
  src/main/java/com/knu/cse/classroom/controller/ClassRoomController.java
  src/main/java/com/knu/cse/classroom/repository/ClassRoomRepository.java
  src/main/java/com/knu/cse/classroom/service/ClassRoomService.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/reservation/controller/ReservationController.java
  src/main/java/com/knu/cse/reservation/repository/ReservationRepository.java
  src/main/java/com/knu/cse/reservation/service/ReservationService.java
Labels: Refactor

#41 FEAT: BoardService(게시물 작성,삭제,검색,내용 수정)
  src/main/java/com/knu/cse/board/controller/BoardController.java
  src/main/java/com/knu/cse/board/domain/Board.java
  src/main/java/com/knu/cse/board/dto/BoardDto.java
  src/main/java/com/knu/cse/board/dto/BoardForm.java
  src/main/java/com/knu/cse/board/repository/BoardRepository.java
  src/main/java/com/knu/cse/board/service/BoardService.java
Labels: enhancement

#45 FIX: ApiUtils.success 를 static import
  src/main/java/com/knu/cse/classroom/controller/ClassRoomController.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/reservation/controller/ReservationController.java
Labels: Refactor

#46 CHORE: .yml 파일 버전 관리에서 제거 및 빌드
  .gitignore
  src/main/resources/application.yml
  src/test/java/com/knu/cse/AuthServiceTest.java
Labels: bug

#47 FEAT: Amazon S3 에 이미지 업로드 기능 구현
  build.gradle
  src/main/java/com/knu/cse/HealthCheckController.java
  src/main/java/com/knu/cse/image/S3UploadController.java
  src/main/java/com/knu/cse/image/S3UploadService.java
Labels: Establish, enhancement

#50 FEAT: 이메일 인증 - 인증 코드 방식 구현
  src/main/java/com/knu/cse/email/service/AuthService.java
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/dto/RequestVerifyEmail.java
  src/main/java/com/knu/cse/member/dto/SignUpForm.java
  src/main/java/com/knu/cse/member/dto/VerifyEmailDto.java
  src/main/java/com/knu/cse/reservation/controller/ReservationController.java
Labels: enhancement

#52 FEAT: 프로필 이미지 등록 및 조회 기능 구현
  src/main/java/com/knu/cse/member/controller/MemberController.java
  src/main/java/com/knu/cse/member/dto/MemberDto.java
  src/main/java/com/knu/cse/member/model/Member.java
  src/main/java/com/knu/cse/member/service/MemberService.java
Labels: enhancement
